### ISSUE TITLE
请问安装之后如何使用？

### ISSUE THREAD

**Issue by IDONKN** [P3TERX/aria2.sh#10]
想使用aria2c -i list.txt

但是报错如下
02/26 15:22:36 [NOTICE] Downloading 1986 item(s)

02/26 15:22:36 [ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use

02/26 15:22:37 [ERROR] Exception caught

**Comment by P3TERX** [comment]
这个安装脚本主要是用于通过 RPC 方式去使用的，安装后配置文件会在默认的位置，如果使用 CLI 方式使用会读取配置文件去开启 RPC 连接，所以就导致了这个错误。你可以尝试指定一个空的配置文件。
