### ISSUE TITLE
aria2安装完成后不管下载什么都直接错误

### ISSUE THREAD

**Issue by Burchencode** [P3TERX/aria2.sh#16]
进去新建下载的时候，文件直接错误，已停止那个界面文件显示下载了0 ，有个红叉后面是重试。

**Comment by Burchencode** [comment]
这是日志文件

04/23 16:41:38 [ERROR] CUID#146 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:557] errNum=95 errorCode=17 fallocate failed. cause: 不支持的操作

04/23 16:41:38 [ERROR] CUID#146 - Download not complete: /data/download/sogou_pinyin_97a.exe
04/23 16:41:38 [INFO] Download error or stop, start deleting files...

**Comment by P3TERX** [comment]
fallocate failed. cause
