### ISSUE TITLE
大佬，能不能添加下载任务筛选功能呢？

### ISSUE THREAD

**Issue by cgkings** [P3TERX/aria2.sh#18]
如题，一下添加了几千个任务，等了10几分钟才添加进去，但是有些正在下载的任务视频下载完了，因为一些垃圾文件卡在那不能动，请问怎么自动下载任务筛选啊，比如说只选择下载视频文件
我看autoupload.sh有筛选上传

**Comment by P3TERX** [comment]
暂停后手动选就行了，那个脚本是下载完后删除
