### ISSUE TITLE
安装这个后,,,远程可以连接到了,,但是,服务器上用aria2c的命令不能下载了

### ISSUE THREAD

**Issue by anlen123** [P3TERX/aria2.sh#19]
安装这个后,,,远程可以连接到了,,但是,服务器上用aria2c的命令不能下载了

**Comment by P3TERX** [comment]
这个问题之前就有注意到，原因是脚本安装后配置文件会放在默认位置，只要执行`aria2c`就会去读取，由于配置文件是适用于 RPC 服务的，所以执行`aria2c`会开启 RPC 服务而不是去下载。移动配置文件到一个非默认位置，修改启动脚本中的配置文件位置就能解决。这个改动意味着需要卸载重装，除非有一个迁移方案才能做平滑升级，所以一直咕咕咕没有去改。

就目前来说，可以使用`--no-conf`选项禁用配置文件：
```
aria2c --no-conf https://xxx.xxx.xxx
```

**Comment by P3TERX** [comment]
更新了一波，现在已经可以直接使用了。

**Comment by anlen123** [comment]
还有就是,,卸载后,aria2用不了,说找不到目录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"P3TERX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午3:34
收件人:&nbsp;"P3TERX/aria2.sh"<aria2.sh@noreply.github.com&gt;;
抄送:&nbsp;"1761512493"<1761512493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [P3TERX/aria2.sh] 安装这个后,,,远程可以连接到了,,但是,服务器上用aria2c的命令不能下载了 (#19)





 
更新了一波，现在已经可以直接使用了。

**Comment by anlen123** [comment]
用sudo 就可以了,,我不懂为啥用sudo 就行,,我明明是root账户,,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"P3TERX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 下午3:34
收件人:&nbsp;"P3TERX/aria2.sh"<aria2.sh@noreply.github.com&gt;;
抄送:&nbsp;"1761512493"<1761512493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [P3TERX/aria2.sh] 安装这个后,,,远程可以连接到了,,但是,服务器上用aria2c的命令不能下载了 (#19)





 
更新了一波，现在已经可以直接使用了。
