### ISSUE TITLE
Aria2安装后 启动失败

### ISSUE THREAD

**Issue by vantexi** [P3TERX/aria2.sh#20]
[信息] Aria2 启动中...
/etc/init.d/aria2: line 72: 16972 Segmentation fault      nohup aria2c --conf-path="${CONFIG}" >> "${LOG}" 2>&1
[错误] Aria2 启动失败 !

**Comment by heany** [comment]
请问你是怎么解决的，我也遇到相同问题，ubuntu系统下
[信息] Aria2 启动中...
/etc/init.d/aria2: line 77: 41235 Segmentation fault      nohup /usr/local/bin/aria2c --conf-path="${CONFIG}" >> "${LOG}" 2>&1
[错误] Aria2 启动失败 !
