### ISSUE TITLE
Aria2 启动失败

### ISSUE THREAD

**Issue by Coolkkmeat** [P3TERX/aria2.sh#23]
CentOS 8
```
[信息] Aria2 启动中...
/etc/init.d/aria2: 行 78: 18634 段错误               nohup aria2c --conf-path="${CONFIG}" >> "${LOG}" 2>&1
[错误] Aria2 启动失败 !
```

**Comment by Coolkkmeat** [comment]
还有在卸载的时候：
```
./aria2.sh:行622: update-rc.d: 未找到命令
```

**Comment by Captain-Space** [comment]
同啊，启动失败

**Comment by Coolkkmeat** [comment]
解决了，语言设置问题。在`～/.bashrc`最后添加`export LC_ALL=C`即可。

**Comment by Coolkkmeat** [comment]
> 同啊，启动失败

解决了，↑

**Comment by i704226922** [comment]
同样的问题，在～/.bashrc最后添加export LC_ALL=C没有效果额

**Comment by i704226922** [comment]
> 解决了，语言设置问题。在`～/.bashrc`最后添加`export LC_ALL=C`即可。

我的没有解决，我在.bashrc这个文件最后一段加上了`export LC_ALL=C`还是启动失败

**Comment by i704226922** [comment]
[信息] Aria2 启动中...
/etc/init.d/aria2: line 78:  6616 Segmentation fault      nohup aria2c --conf-path="${CONFIG}" >> "${LOG}" 2>&1
[错误] Aria2 启动失败 !

**Comment by lccsw** [comment]
我也是这样，求解
