### ISSUE TITLE
aria2能不能同时上传到多个网盘？

### ISSUE THREAD

**Issue by qingchencjg** [P3TERX/aria2.sh#30]
我在配置RCLONE时设置了多个OneDrive网盘，
![image](https://user-images.githubusercontent.com/65435648/89004012-ccbdb900-d333-11ea-9a32-ee060a322e5c.png)
这里只能填写一个name吗？，如果可以多个，需要怎么设置。。。

**Comment by P3TERX** [comment]
只能一个，特殊需求自己写脚本
