### ISSUE TITLE
脚本判断错误,  提示: Aria2 没有安装，请检查

### ISSUE THREAD

**Issue by cmdegr** [P3TERX/aria2.sh#4]
我使用这个博客: https://www.moerats.com/archives/517/  提供的一键安装脚本安装的Aria2. 
实际我已经成功安装了Aria2,  但是当我使用Aria2 一键安装管理脚本 [v2.10.0] 时,
脚本提示我: Aria2未安装.

应该是 19行的 aria2c="/usr/local/bin/aria2c"
我通过脚本安装的aria2这里是没有local的,  希望大佬能改善一下.

**Comment by cmdegr** [comment]
在54行的判断, 能不能多加一个判断,  当aria2c="/usr/bin/aria2c"时 也能成功判断.

**Comment by P3TERX** [comment]
脚本不要混用，容易出问题。

之前的脚本有很多历史遗留问题，所以我做出了一些改动，就比如把`/usr/bin`改为`/usr/local/bin`。

`/usr/bin`这个目录是存放系统包管理器安装软件的位置，如果之前通过包管理器安装了 Aria2 ，脚本会检测到已安装。这样问题就来了，不是通过脚本安装的它没有启动脚本和配置文件，所以就没办法正常去使用脚本。

**Comment by cmdegr** [comment]
首先, 谢谢大佬的回复.
我已经重装系统了,  全部用大佬开发的脚本, 脚本很好用, 再次谢谢大佬开发出这么方便的脚本, 省了很多事情.
