### ISSUE TITLE
Aria2 启动失败 nohup aria2c >> "${LOG}" 2>&1

### ISSUE THREAD

**Issue by ReddotCleaner** [P3TERX/aria2.sh#6]
[信息] Aria2 启动中...
/etc/init.d/aria2: line 67:  2995 Aborted                 nohup aria2c >> "${LOG}" 2>&1
[错误] Aria2 启动失败 !

log:
aria2c: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

**Comment by P3TERX** [comment]
语言设置问题，自行 Gooogle 解决。

**Comment by i704226922** [comment]
谷歌搜不出来额，这个该怎么解决

**Comment by ReddotCleaner** [comment]
> 谷歌搜不出来额，这个该怎么解决

尝试在普通用户下sudo 启动
