### ISSUE TITLE
安装成功后的rpc-secret和配置文件不匹配

### ISSUE THREAD

**Issue by vcan** [P3TERX/aria2.sh#7]
安装成功后提示
地址    : 1xx.1xx.1xx.195
 端口    : 6800
 密钥    : c4ff2328459222b58847
 目录    : /root/Download

但是vim打开/root/.aria2/aria2.conf
发现配置的rpc-secret=999b1742ca0a7b90fea1
不匹配，导致无法认证成功。
按照conf中的秘钥设置就可以成功。不清楚原因请检查下代码。

**Comment by P3TERX** [comment]
相关代码一直没有改动，无法复现。

**Comment by vcan** [comment]
> 相关代码一直没有改动，无法复现。

感谢回复，可能是我用vim修改了/root/.aria2/aria2.conf配置文件，没用重启aria2导致的。后来也没有再复现这个问题。
