### ISSUE TITLE
file I/O error occurred 

### ISSUE THREAD

**Issue by vcan** [P3TERX/aria2.sh#9]
系统配置Centos7 

02/25 08:34:18 [ERROR] Error when trying to flush write cache
Exception: [AbstractDiskWriter.cc:459] errNum=29 errorCode=17 Failed to write into the file /home/gdrive/android-studio-ide-192.6200805-mac.dmg, cause: Illegal seek

**Comment by P3TERX** [comment]
1. 目录没有写入权限
2. 文件系统或内核不支持 fal­loc 文件分配方式。可尝试修改配置文件的第 51 行`file-allocation`参数为`none`，并重启 Aria2 。
3. 善用搜索。

**Comment by vcan** [comment]
> 1. 目录没有写入权限
> 2. 文件系统或内核不支持 fal­loc 文件分配方式。可尝试修改配置文件的第 51 行`file-allocation`参数为`none`，并重启 Aria2 。
> 3. 善用搜索。

感谢回复，问题解决了。
原因在于我参考的教程有问题，把谷歌云盘设置成了下载目录，导致无法写入。
